using System.Collections.Generic;
using Unity.Collections;
using Unity.Entities;
using UnityEngine;

namespace DMotion.Authoring
{
    public abstract class AnimationParameterAsset : StateMachineSubAsset
    {
        public int Hash => StateMachineParameterUtils.GetHashCode(name);

        public abstract string ParameterTypeName { get; }

        #region Dependency Tracking

        /// <summary>
        /// True if this parameter was auto-generated to satisfy a SubStateMachine requirement.
        /// Auto-generated parameters can be safely deleted when no longer needed.
        /// </summary>
        [SerializeField, HideInInspector]
        private bool _isAutoGenerated;

        /// <summary>
        /// List of SubStateMachines that require this parameter.
        /// Used for orphan detection and dependency visualization.
        /// </summary>
        [SerializeField, HideInInspector]
        private List<SubStateMachineStateAsset> _requiredBySubMachines = new();

        /// <summary>
        /// True if this parameter was auto-generated due to SubStateMachine requirements.
        /// </summary>
        public bool IsAutoGenerated
        {
            get => _isAutoGenerated;
            internal set => _isAutoGenerated = value;
        }

        /// <summary>
        /// SubStateMachines that require this parameter.
        /// </summary>
        public IReadOnlyList<SubStateMachineStateAsset> RequiredBySubMachines => _requiredBySubMachines;

        /// <summary>
        /// Marks this parameter as required by a SubStateMachine.
        /// </summary>
        internal void AddRequiredBy(SubStateMachineStateAsset subMachine)
        {
            if (subMachine != null && !_requiredBySubMachines.Contains(subMachine))
            {
                _requiredBySubMachines.Add(subMachine);
            }
        }

        /// <summary>
        /// Removes a SubStateMachine from the required-by list.
        /// </summary>
        internal void RemoveRequiredBy(SubStateMachineStateAsset subMachine)
        {
            _requiredBySubMachines.Remove(subMachine);
        }

        /// <summary>
        /// Clears all dependency tracking. Use when parameter is being deleted or reset.
        /// </summary>
        internal void ClearDependencies()
        {
            _requiredBySubMachines.Clear();
        }

        /// <summary>
        /// Returns true if this parameter has no SubStateMachine dependencies.
        /// Auto-generated orphan parameters are safe to delete.
        /// </summary>
        public bool IsOrphan => _requiredBySubMachines.Count == 0;

        #endregion
    }
}